apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore_app
  title: Petstore demo project 
  description: |
    Aplicación demo petstore
  links:
    - title: Acceso petstore
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/
    - title: API petstore
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com//swagger-ui/
    - title: Wiki petstore
      url: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/wiki
    - title: Sharepoint Doc (Deprecated)
      url: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/wiki/Sharepoint-Documentation-REPO
  annotations:
    backstage.io/kubernetes-id: app-spring-petclinic
    backstage.io/kubernetes-namespace: pets
    backstage.io/kubernetes-label-selector: 'app=app-spring-petclinic'
    jenkins.io/job-full-name: [https://jenkins-devops-toolset.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/job/petstore/]
spec: 
  type: website
  owner: departamento_desarrollo_software
  providesApis:
    - petstore_api
  lifecycle: development
  system: petstore
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: petstore_db
  title: PostgreSQL Database petstore
  description: PostgreSQL is a powerful, open source object-relational database system.
  links:
    - url: https://www.postgresql.org
      title: PostgreSQL website
      icon: web
    - url: https://postgresql.org/docs
      title: PostgreSQL Documentation
      icon: web
  annotations:
    backstage.io/kubernetes-id: mysql
    backstage.io/kubernetes-namespace: pets
    backstage.io/kubernetes-label-selector: 'app=mysql'
spec:
  type: database
  lifecycle: development
  system: petstore
  dependsOn:
    - component:petstore_app
  owner: departamento_desarrollo_software
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: petstore
  title: Petstore System
spec:
  owner: departamento_desarrollo_software
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore_api
  title: Petstore Backend API
  description: |
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
  links:
    - title: Petstore
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/
    - title: Petstore API
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/swagger-ui/
spec:
  type: openapi
  lifecycle: development
  system: petstore
  owner: departamento_desarrollo_software
  definition:
    $openapi: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/blob/main/petstore_swagger.yaml
    
