apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore_website
  title: Petstore demo project 
  description: |
    Aplicación demo petstore
  links:
    - title: Acceso petstore
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/
    - title: API petstore
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/swagger-ui/
    - title: Wiki petstore
      url: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/wiki
#   - title: Issues petstore
#      url: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/pulse
  annotations:
    backstage.io/kubernetes-id: app-spring-petclinic
    backstage.io/kubernetes-namespace: petstore
    backstage.io/kubernetes-label-selector: 'app=app-spring-petclinic'
#    backstage.io/techdocs-ref: dir:.
#    jenkins.io/job-full-name: "instanceName:https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/blob/main/jenkinsfile"
spec: 
  type: website
  owner: departamento_desarrollo_software
  providesApis:
    - petstore_api
  lifecycle: development
  system: petstore
  parent: petstore
  children: [petstore_db, petstore_api]
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: petstore_db
  title: Petstore PostgreSQL Database 
  description: PostgreSQL is a powerful, open source object-relational database system.
  links:
    - url: https://www.postgresql.org
      title: PostgreSQL website
      icon: web
    - url: https://postgresql.org/docs
      title: PostgreSQL Documentation
      icon: web
  annotations:
    backstage.io/kubernetes-id: mysql
    backstage.io/kubernetes-namespace: petstore
    backstage.io/kubernetes-label-selector: 'app_rhdh=mysql_petclinic'
spec:
  type: database
  lifecycle: development
  system: petstore
  domain: 
  owner: departamento_desarrollo_software
  dependsOn: petstore_website
  parent: petstore_website
  
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: petstore
  title: Petstore System
spec:
  owner: departamento_desarrollo_software
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore_api
  title: Petstore Backend API
  description: |
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
  links:
    - title: Petstore
      url: https://app-spring-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/
    - title: Petstore API
      url: https://app-spring-petclinic-pets.apps.cluster-fskhx.fskhx.sandbox1721.opentlc.com/swagger-ui/
    - title: Wiki petstore
      url: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/wiki
spec:
  type: openapi
  system: petstore
  lifecycle: development
  owner: departamento_desarrollo_software
  dependsOn: petstore_website
  parent: petstore_website  
  definition:
    $openapi: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic/blob/main/petstore_swagger.yaml
    
