site_name: "petclinic docs"
site_description: "documentación proyecto petclinic"

nav:
  - Home: index.md
  - Section 1:
      - Sub Section 1.1: section1/ss11.md
      - Sub Section 1.2: section1/ss12.md
      - Sub Section 1.3: section1/ss13.md

plugins:
  - techdocs-core