site_name: "petclinic docs"
site_description: "Documentación proyecto petclinic"
repo_url: https://github.com/knowmadmood-poc-rhdevhub/app.spring-petclinic
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Section 1:
      - Sub Section 1.1: section1/ss11.md
      - Sub Section 1.2: section1/ss12.md
      - Sub Section 1.3: section1/ss13.md

plugins:
  - techdocs-core
